# Numpy introduction 

## import 

In [2]:
import numpy as np

## Datatypes and attributes 

In [3]:
a1 = np.array([1,2,3])

In [4]:
a2 = np.array([[1, 2.9, 3.3],
							[4, 5, 6.5]])

In [5]:
a3 = np.array([[[1, 2, 3],
							[4, 5, 6],
							[7, 8, 9]],
							
							[[10, 11, 12],
							[13, 14, 15],
							[16, 17, 18]]]
							)

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 3, 3)

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [11]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
import pandas as pd

In [13]:
df = pd.DataFrame(a1)

In [14]:
df

0
0  1
1  2
2  3

In [15]:
import random
import numpy as np
a4 = np.random.randint(5, size = (2,2,2,4))
a4

array([[[[1, 1, 4, 4],
         [3, 3, 4, 4]],

        [[4, 3, 0, 1],
         [0, 0, 2, 0]]],


       [[[1, 1, 0, 3],
         [3, 4, 1, 3]],

        [[2, 0, 3, 1],
         [0, 4, 3, 2]]]])

In [16]:
a4.ndim

4

In [17]:
a4.shape

(2, 2, 2, 4)

In [18]:
a1

array([1, 2, 3])

In [19]:
ones = np.ones(3)

In [20]:
ones

array([1., 1., 1.])

In [21]:
a1 + ones

array([2., 3., 4.])

In [22]:
ones / a1

array([1.        , 0.5       , 0.33333333])

### Aggregation 
Aggregation = performing the same operation on a number of things.

In [23]:
massive_array = np.random.randint(0, 10000, size=(10000,))
print(massive_array.shape)

(10000,)


In [24]:
massive_array[:10]

array([ 670, 8588, 5227, 2272, 2074, 3978, 4463, 5254, 6351, 5085])

In [25]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

645 µs ± 1.96 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
3.73 µs ± 19.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Reshape and transpose

In [26]:
a2.shape

(2, 3)

In [27]:
a2.reshape(2,3,1)

array([[[1. ],
        [2.9],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [28]:
a2_reshape = a2.reshape(2,3,1)

In [29]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [30]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a2_transposed = a2.T

In [ ]:
a2_transposed

In [ ]:
a2

### Dot product 

In [ ]:
np.random.seed(0)

In [ ]:
mat1 * mat2

In [ ]:
mat1 = np.random.randint(10, size = (5,3))
mat2 = np.random.randint(10, size = (5,3))

In [ ]:
mat1

In [ ]:
mat2

In [ ]:
np.dot(mat1,mat2.T)

### Sorting arrays

In [ ]:
random_array = np.random.randint(10, size = (3,5))
random_array
                                

In [ ]:
np.sort(random_array)

In [ ]:
np.argsort(random_array)

## Numpy in action

 <img src="car.png" />

In [ ]:
#turn this image into a Numpy array in order to manipulate it and use it using what we saw !

In [ ]:
from matplotlib.image import imread

In [ ]:
car = imread('car-photo.png')

In [ ]:
car.shape, car.ndim, print(type(car))

### Nut butter 

In [31]:
np.random.seed(0)
sales_amount = np.random.randint(20, size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [32]:
# create a DataFrame
weekly_sales = pd.DataFrame(sales_amount, index=['Mon','Tue','Wen','Thu','Fri'], columns=['Almond butter','Peanut butter','Cashew butter'])

In [33]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon             12             15              0
Tue              3              3              7
Wen              9             19             18
Thu              4              6             12
Fri              1              6              7

In [34]:
#Create the prices:

In [35]:
prices = np.array([10,8,12])

In [36]:
prices

array([10,  8, 12])

In [40]:
# Create butter prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3), index=['Prices'], columns=['Almond butter','Peanut butter','Cashew butter'])

In [51]:
type(butter_prices)

pandas.core.frame.DataFrame

In [42]:
total_sales = prices.dot(sales_amount.T)

In [43]:
total_sales

array([240, 138, 458, 232, 142])

In [44]:
# Create daily_sales
daily_sales = butter_prices.dot(weekly_sales.T)

In [45]:
daily_sales

Mon  Tue  Wen  Thu  Fri
Prices  240  138  458  232  142

In [46]:
weekly_sales['Total ($)'] = daily_sales.T

In [47]:
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon             12             15              0        240
Tue              3              3              7        138
Wen              9             19             18        458
Thu              4              6             12        232
Fri              1              6              7        142